name: built_value_generator
version: 6.1.4
description: >
  Value types with builders, Dart classes as enums, and serialization.
  This library is the dev dependency.
authors:
- David Morgan <davidmorgan@google.com>
homepage: https://github.com/google/built_value.dart

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  analyzer: ^0.33.0-alpha.0
  analyzer_plugin: # ^0.0.1-alpha.4
    git:
      url: https://github.com/pcejas/sdk.git
      path: pkg/analyzer_plugin
  build: '>=0.12.0 <2.0.0'
  build_config: ^0.3.1
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'
  source_gen: ^0.9.0
  quiver: '>=0.21.0 <3.0.0'

dev_dependencies:
  build_test: ^0.10.0
  build_runner: '>=0.9.0 <0.11.0'
  test: ^1.0.0
